### ISSUE TITLE
errors using molecule-action v5

### ISSUE THREAD

**Issue by abh** [robertdebock/molecule-action#15]
(I'm new to making ansible roles AND GitHub actions, so bear with me!)

In my [ansible-timezone](https://github.com/abh/ansible-timezone/) fork I'm trying to use molecule-action to test. With v5 it fails running molecule missing a parameter, it seems.

In my last test I setup the job so it runs lint with v4 (works) and test with v5 (fails).

```
Usage: molecule [OPTIONS] COMMAND [ARGS]...
Try 'molecule --help' for help.

Error: No such option: --debug test (Possible options: --debug, --no-debug)
ACTION: Retry attempt 1.
Usage: molecule [OPTIONS] COMMAND [ARGS]...
Try 'molecule --help' for help.
```

Example action run: https://github.com/abh/ansible-timezone/actions/runs/5152456387/jobs/9278594310

[workflow file](https://github.com/abh/ansible-timezone/blob/main/.github/workflows/publish-role.yaml)

Also pasted here:

```yaml
---
name: GitHub Action

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        # https://github.com/marketplace/actions/test-ansible-roles-with-molecule
        uses: robertdebock/molecule-action@4.0.9
        with:
          command: lint

  test:
    needs:
      - lint 
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@5.0.3
        with:
          command: "--debug test"

  release:
    needs:
      - test
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: galaxy
        # https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          git_branch: main
```
