### ISSUE TITLE
Options to pass to Molecule command

### ISSUE THREAD

**Issue by kenorb** [robertdebock/molecule-action#6]
I'd like to pass options (such as `-v` or `--debug`) to Molecule command. Is it possible?

**Comment by robertdebock** [comment]
That's not possible now, but it can be built in. Give me some time or make a PR if you've got the time for it.

**Comment by robertdebock** [comment]
You can enable debugging using this pattern:

```
      - name: molecule
        uses: robertdebock/molecule-action@4.0.5
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
          command: "--debug test"
```

I'll update the documentation.
