### ISSUE TITLE
Is it possible to run molecule tests in a subdirectory of a repository?

### ISSUE THREAD

**Issue by konstantin-kornienko** [robertdebock/molecule-action#9]
Tried this (looks like cmd.sh uses GITHUB_REPOSITORY env var) , but it doesn't work...

```
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Run Molecule
        uses: robertdebock/molecule-action@2.6.17
        env:
          max_failures: 1
          GITHUB_REPOSITORY: my/sub/dir
```
